# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 699)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStatusTip("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setEnabled(True)
        self.tab_12.setObjectName("tab_12")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_19 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_12)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_12)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setOpenExternalLinks(True)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.label_38 = QtWidgets.QLabel(self.tab_12)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_10.addWidget(self.label_38)
        self.label_23 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_10.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_10.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.tab_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_12, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_42 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.label_42)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setStyleSheet("QAbstractScrollArea\n"
"{\n"
"background-color: transparent;\n"
"}\n"
"QWidget#scrollAreaWidgetContents{\n"
"background-color: transparent; /*or a colour*/\n"
"} ")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1021, 828))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setOpenExternalLinks(True)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_5.addWidget(self.pushButton_15)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setOpenExternalLinks(True)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_7)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setOpenExternalLinks(True)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_8.addWidget(self.pushButton_17)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setOpenExternalLinks(True)
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setClearButtonEnabled(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_9.addWidget(self.pushButton_9)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_9.addWidget(self.pushButton_18)
        self.formLayout_6.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_9)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setOpenExternalLinks(True)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setClearButtonEnabled(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setClearButtonEnabled(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_10.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_10.addWidget(self.pushButton_20)
        self.formLayout_7.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_10)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setOpenExternalLinks(True)
        self.label_35.setObjectName("label_35")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.sourcesTabs = QtWidgets.QTabWidget(self.tab_2)
        self.sourcesTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.sourcesTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.sourcesTabs.setElideMode(QtCore.Qt.ElideNone)
        self.sourcesTabs.setUsesScrollButtons(True)
        self.sourcesTabs.setTabsClosable(False)
        self.sourcesTabs.setTabBarAutoHide(False)
        self.sourcesTabs.setObjectName("sourcesTabs")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_5)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_11.addWidget(self.treeWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 484, 461))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_5.addWidget(self.pushButton_23)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_11)
        self.sourcesTabs.addTab(self.tab_5, "")
        self.verticalLayout_8.addWidget(self.sourcesTabs)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_14.addWidget(self.pushButton_12)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.queueTools = QtWidgets.QVBoxLayout()
        self.queueTools.setObjectName("queueTools")
        self.toolButton = QtWidgets.QToolButton(self.tab_3)
        self.toolButton.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("up")
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.queueTools.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_2.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("down")
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.queueTools.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_3.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("edit")
        self.toolButton_3.setIcon(icon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.queueTools.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_4.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("remove")
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.queueTools.addWidget(self.toolButton_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.queueTools.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.queueTools)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tableWidget_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuBackups = QtWidgets.QMenu(self.menuOpen)
        self.menuBackups.setObjectName("menuBackups")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAPI_Key_file = QtWidgets.QAction(MainWindow)
        self.actionAPI_Key_file.setObjectName("actionAPI_Key_file")
        self.actionScraping_state = QtWidgets.QAction(MainWindow)
        self.actionScraping_state.setObjectName("actionScraping_state")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicenses = QtWidgets.QAction(MainWindow)
        self.actionLicenses.setObjectName("actionLicenses")
        self.actionAPI_Keys = QtWidgets.QAction(MainWindow)
        self.actionAPI_Keys.setObjectName("actionAPI_Keys")
        self.actionJob_Queue = QtWidgets.QAction(MainWindow)
        self.actionJob_Queue.setObjectName("actionJob_Queue")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionReport_a_bug = QtWidgets.QAction(MainWindow)
        self.actionReport_a_bug.setObjectName("actionReport_a_bug")
        self.actionScraping = QtWidgets.QAction(MainWindow)
        self.actionScraping.setCheckable(True)
        self.actionScraping.setChecked(True)
        self.actionScraping.setObjectName("actionScraping")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setCheckable(True)
        self.actionHistory.setObjectName("actionHistory")
        self.actionHistory_2 = QtWidgets.QAction(MainWindow)
        self.actionHistory_2.setObjectName("actionHistory_2")
        self.actionAPI_Key_Database = QtWidgets.QAction(MainWindow)
        self.actionAPI_Key_Database.setObjectName("actionAPI_Key_Database")
        self.actionAdvanced_mode = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_mode.setCheckable(True)
        self.actionAdvanced_mode.setObjectName("actionAdvanced_mode")
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionQueue = QtWidgets.QAction(MainWindow)
        self.actionQueue.setObjectName("actionQueue")
        self.actionJob = QtWidgets.QAction(MainWindow)
        self.actionJob.setObjectName("actionJob")
        self.menuBackups.addAction(self.actionQueue)
        self.menuBackups.addAction(self.actionJob)
        self.menuOpen.addAction(self.actionAPI_Key_file)
        self.menuOpen.addAction(self.actionJob_Queue)
        self.menuOpen.addAction(self.actionScraping_state)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.menuBackups.menuAction())
        self.menuSave.addAction(self.actionAPI_Keys)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionReport_a_bug)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicenses)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWebsite)
        self.menuView.addAction(self.actionHistory_2)
        self.menuView.addAction(self.actionAPI_Key_Database)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAdvanced_mode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.sourcesTabs.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reaper"))
        MainWindow.setStatusTip(_translate("MainWindow", "Visit https://reaper.social for help & tutorials"))
        self.label_19.setText(_translate("MainWindow", "Welcome to Reaper!"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>© The University of Queensland</p><p>Developed by <a href=\"https://github.com/ScriptSmith\"><span style=\" text-decoration: underline; color:#0000ff;\">Adam Smith</span></a></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Reaper helps you gather social media data, no coding required."))
        self.label_23.setText(_translate("MainWindow", "Simply:"))
        self.label_24.setText(_translate("MainWindow", "1. Add & verify your API Keys"))
        self.label_25.setText(_translate("MainWindow", "2. Input your parameters"))
        self.label_26.setText(_translate("MainWindow", "3. Add your scraping instruction to the queue"))
        self.label_27.setText(_translate("MainWindow", "4. Download your data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "0. Introduction"))
        self.label_42.setText(_translate("MainWindow", "By using these platforms, you are agreeing to their terms & conditions"))
        self.groupBox.setTitle(_translate("MainWindow", "Facebook"))
        self.label.setText(_translate("MainWindow", "Access Token"))
        self.pushButton_2.setText(_translate("MainWindow", "Verify"))
        self.pushButton_14.setText(_translate("MainWindow", "Add to DB"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Twitter"))
        self.label_2.setText(_translate("MainWindow", "Consumer Key"))
        self.label_3.setText(_translate("MainWindow", "Consumer Secret"))
        self.label_4.setText(_translate("MainWindow", "Access Token"))
        self.label_5.setText(_translate("MainWindow", "Access Token Secret"))
        self.pushButton_3.setText(_translate("MainWindow", "Verify"))
        self.pushButton_15.setText(_translate("MainWindow", "Add to DB"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reddit"))
        self.label_6.setText(_translate("MainWindow", "Identifier"))
        self.label_7.setText(_translate("MainWindow", "Secret"))
        self.pushButton_4.setText(_translate("MainWindow", "Verify"))
        self.pushButton_16.setText(_translate("MainWindow", "Add to DB"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "YouTube"))
        self.label_8.setText(_translate("MainWindow", "Key"))
        self.pushButton_8.setText(_translate("MainWindow", "Verify"))
        self.pushButton_17.setText(_translate("MainWindow", "Add to DB"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Tumblr"))
        self.label_12.setText(_translate("MainWindow", "Key"))
        self.label_13.setText(_translate("MainWindow", "Secret"))
        self.pushButton_9.setText(_translate("MainWindow", "Verify"))
        self.pushButton_18.setText(_translate("MainWindow", "Add to DB"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "LinkedIn"))
        self.label_17.setText(_translate("MainWindow", "Client Id"))
        self.label_18.setText(_translate("MainWindow", "Client Secret"))
        self.pushButton_19.setText(_translate("MainWindow", "Verify"))
        self.pushButton_20.setText(_translate("MainWindow", "Add to DB"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"http://reaper.social\"><span style=\" text-decoration: underline; color:#0000ff;\">How do I get this?</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1. API Keys"))
        self.label_14.setText(_translate("MainWindow", "Select the source that you want to scrape from"))
        self.label_15.setText(_translate("MainWindow", "Double-click a node to see and select its edges"))
        self.pushButton_23.setText(_translate("MainWindow", "PushButton"))
        self.sourcesTabs.setTabText(self.sourcesTabs.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.pushButton_12.setText(_translate("MainWindow", "Next"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2. Sources"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Job 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Job 2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "File path"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Parameters"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "API Keys"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_29.setText(_translate("MainWindow", "Queue Controls"))
        self.pushButton_6.setText(_translate("MainWindow", "Start"))
        self.pushButton_10.setText(_translate("MainWindow", "Stop"))
        self.pushButton_11.setText(_translate("MainWindow", "Clear"))
        self.pushButton_5.setText(_translate("MainWindow", "Save Queue to file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "3. Job Queue"))
        self.label_9.setText(_translate("MainWindow", "Progress:"))
        self.pushButton.setText(_translate("MainWindow", "Pause"))
        self.label_10.setText(_translate("MainWindow", "0/100"))
        self.pushButton_7.setText(_translate("MainWindow", "Save Progress to file"))
        self.label_21.setText(_translate("MainWindow", "Note: Only a subset of the downloading data is displayed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "4. Current Job"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuBackups.setTitle(_translate("MainWindow", "Backups"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAPI_Key_file.setText(_translate("MainWindow", "API Keys"))
        self.actionScraping_state.setText(_translate("MainWindow", "Scraping state"))
        self.actionAbout.setText(_translate("MainWindow", "About Reaper"))
        self.actionLicenses.setText(_translate("MainWindow", "Licenses"))
        self.actionAPI_Keys.setText(_translate("MainWindow", "API Keys"))
        self.actionJob_Queue.setText(_translate("MainWindow", "Job Queue"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug"))
        self.actionScraping.setText(_translate("MainWindow", "Scraping"))
        self.actionHistory.setText(_translate("MainWindow", "History"))
        self.actionHistory_2.setText(_translate("MainWindow", "History"))
        self.actionAPI_Key_Database.setText(_translate("MainWindow", "API Key Database"))
        self.actionAdvanced_mode.setText(_translate("MainWindow", "Advanced mode"))
        self.actionWebsite.setText(_translate("MainWindow", "Website"))
        self.actionQueue.setText(_translate("MainWindow", "Queue"))
        self.actionJob.setText(_translate("MainWindow", "Job"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

