# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 1354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1184, 1518))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_9)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fb_stack = QtWidgets.QStackedWidget(self.tab_5)
        self.fb_stack.setObjectName("fb_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_3)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_5.addWidget(self.treeWidget)
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.fb_next = QtWidgets.QPushButton(self.page_3)
        self.fb_next.setObjectName("fb_next")
        self.verticalLayout_5.addWidget(self.fb_next)
        self.fb_stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.fb_stack.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.fb_stack)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.formLayout_5 = QtWidgets.QFormLayout(self.tab_10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.progressBar = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_2)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 39))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAPI_Key_file = QtWidgets.QAction(MainWindow)
        self.actionAPI_Key_file.setObjectName("actionAPI_Key_file")
        self.actionScraping_state = QtWidgets.QAction(MainWindow)
        self.actionScraping_state.setObjectName("actionScraping_state")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicenses = QtWidgets.QAction(MainWindow)
        self.actionLicenses.setObjectName("actionLicenses")
        self.actionAPI_Keys = QtWidgets.QAction(MainWindow)
        self.actionAPI_Keys.setObjectName("actionAPI_Keys")
        self.actionJob_Queue = QtWidgets.QAction(MainWindow)
        self.actionJob_Queue.setObjectName("actionJob_Queue")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionReport_a_bug = QtWidgets.QAction(MainWindow)
        self.actionReport_a_bug.setObjectName("actionReport_a_bug")
        self.menuOpen.addAction(self.actionAPI_Key_file)
        self.menuOpen.addAction(self.actionJob_Queue)
        self.menuOpen.addAction(self.actionScraping_state)
        self.menuSave.addAction(self.actionAPI_Keys)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicenses)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionReport_a_bug)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.fb_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Facebook"))
        self.label.setText(_translate("MainWindow", "Access Token"))
        self.pushButton.setText(_translate("MainWindow", "Verify"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Twitter"))
        self.label_2.setText(_translate("MainWindow", "Consumer Key"))
        self.label_3.setText(_translate("MainWindow", "Consumer Secret"))
        self.label_4.setText(_translate("MainWindow", "Access Token"))
        self.label_5.setText(_translate("MainWindow", "Access Token Secret"))
        self.pushButton_2.setText(_translate("MainWindow", "Verify"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reddit"))
        self.label_6.setText(_translate("MainWindow", "Identifier"))
        self.label_7.setText(_translate("MainWindow", "Secret"))
        self.pushButton_3.setText(_translate("MainWindow", "Verify"))
        self.groupBox_4.setTitle(_translate("MainWindow", "YouTube"))
        self.label_8.setText(_translate("MainWindow", "Key"))
        self.pushButton_4.setText(_translate("MainWindow", "Verify"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Tumblr"))
        self.label_12.setText(_translate("MainWindow", "Key"))
        self.label_13.setText(_translate("MainWindow", "Secret"))
        self.pushButton_8.setText(_translate("MainWindow", "Verify"))
        self.groupBox_6.setTitle(_translate("MainWindow", "LinkedIn"))
        self.label_17.setText(_translate("MainWindow", "Client Id"))
        self.label_18.setText(_translate("MainWindow", "Client Secret"))
        self.pushButton_9.setText(_translate("MainWindow", "Verify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "API Keys"))
        self.label_14.setText(_translate("MainWindow", "Select the source that you want to scrape from"))
        self.label_15.setText(_translate("MainWindow", "Double-click a node to see and select its edges"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Nodes"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Page"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Posts"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Events"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Admins"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Attending"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "Declined"))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "Feed"))
        self.treeWidget.topLevelItem(0).child(1).child(4).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(1).child(4).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(1).child(4).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(1).child(4).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(1).child(4).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(0).child(1).child(5).setText(0, _translate("MainWindow", "Interested"))
        self.treeWidget.topLevelItem(0).child(1).child(6).setText(0, _translate("MainWindow", "Live_Videos"))
        self.treeWidget.topLevelItem(0).child(1).child(7).setText(0, _translate("MainWindow", "Maybe"))
        self.treeWidget.topLevelItem(0).child(1).child(8).setText(0, _translate("MainWindow", "NoReply"))
        self.treeWidget.topLevelItem(0).child(1).child(9).setText(0, _translate("MainWindow", "Photos"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(4).setText(0, _translate("MainWindow", "Sponsor_Tags"))
        self.treeWidget.topLevelItem(0).child(1).child(9).child(5).setText(0, _translate("MainWindow", "Tags"))
        self.treeWidget.topLevelItem(0).child(1).child(10).setText(0, _translate("MainWindow", "Picture"))
        self.treeWidget.topLevelItem(0).child(1).child(11).setText(0, _translate("MainWindow", "Roles"))
        self.treeWidget.topLevelItem(0).child(1).child(12).setText(0, _translate("MainWindow", "Videos"))
        self.treeWidget.topLevelItem(0).child(1).child(12).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(1).child(12).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(1).child(12).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(1).child(12).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(1).child(12).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Albums"))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "Picture"))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "Photos"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(4).setText(0, _translate("MainWindow", "Sponsor_Tags"))
        self.treeWidget.topLevelItem(0).child(2).child(1).child(5).setText(0, _translate("MainWindow", "Tags"))
        self.treeWidget.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(2).child(3).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(2).child(4).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(2).child(5).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Photos"))
        self.treeWidget.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(3).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(3).child(4).setText(0, _translate("MainWindow", "Sponsor_Tags"))
        self.treeWidget.topLevelItem(0).child(3).child(5).setText(0, _translate("MainWindow", "Tags"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Videos"))
        self.treeWidget.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(0).child(4).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(0).child(4).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(0).child(4).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "Picture"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "Misc. node"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Event"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Admins"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Attending"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Declined"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "Feed"))
        self.treeWidget.topLevelItem(1).child(4).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(1).child(4).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(1).child(4).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(1).child(4).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(1).child(4).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "Interested"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "Live_Videos"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "Maybe"))
        self.treeWidget.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "NoReply"))
        self.treeWidget.topLevelItem(1).child(9).setText(0, _translate("MainWindow", "Photos"))
        self.treeWidget.topLevelItem(1).child(9).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(1).child(9).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(1).child(9).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(1).child(9).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(1).child(9).child(4).setText(0, _translate("MainWindow", "Sponsor_Tags"))
        self.treeWidget.topLevelItem(1).child(9).child(5).setText(0, _translate("MainWindow", "Tags"))
        self.treeWidget.topLevelItem(1).child(10).setText(0, _translate("MainWindow", "Picture"))
        self.treeWidget.topLevelItem(1).child(11).setText(0, _translate("MainWindow", "Roles"))
        self.treeWidget.topLevelItem(1).child(12).setText(0, _translate("MainWindow", "Videos"))
        self.treeWidget.topLevelItem(1).child(12).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(1).child(12).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(1).child(12).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(1).child(12).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(1).child(12).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Post"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "Attachments"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Comment"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Album"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Picture"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Photos"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Photo"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Likes"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Reactions"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Comments"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "SharedPosts"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Sponsor_Tags"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "Tags"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("MainWindow", "I want to scrape a Facebook X\'s Y\'s Zs"))
        self.fb_next.setText(_translate("MainWindow", "Next"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Facebook"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Twitter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Reddit"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "YouTube"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Tumblr"))
        self.label_11.setText(_translate("MainWindow", "Not available in this version of Reaper"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Instagram"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "LinkedIn"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sources"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Row 2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "File path"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Parameters"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "API Keys"))
        self.pushButton_5.setText(_translate("MainWindow", "Save Queue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Job Queue"))
        self.label_9.setText(_translate("MainWindow", "Progress:"))
        self.label_10.setText(_translate("MainWindow", "0/100"))
        self.label_21.setText(_translate("MainWindow", "Note: Only a subset of the downloading data is displayed"))
        self.pushButton_7.setText(_translate("MainWindow", "Save Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Current Job"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAPI_Key_file.setText(_translate("MainWindow", "API Keys"))
        self.actionScraping_state.setText(_translate("MainWindow", "Scraping state"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLicenses.setText(_translate("MainWindow", "Licenses"))
        self.actionAPI_Keys.setText(_translate("MainWindow", "API Keys"))
        self.actionJob_Queue.setText(_translate("MainWindow", "Job Queue"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

