# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/facebook/post.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 1718)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 662, 1652))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_4 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_36.setObjectName("checkBox_36")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_36)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_37.setObjectName("checkBox_37")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_37)
        self.checkBox_38 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_38.setObjectName("checkBox_38")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_38)
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_39.setObjectName("checkBox_39")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_39)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_2)
        self.checkBox_40 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_40.setObjectName("checkBox_40")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_40)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setObjectName("checkBox_10")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setObjectName("checkBox_11")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_12.setObjectName("checkBox_12")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setObjectName("checkBox_13")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setObjectName("checkBox_14")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setObjectName("checkBox_15")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setObjectName("checkBox_16")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_17.setObjectName("checkBox_17")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_18.setObjectName("checkBox_18")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_19.setObjectName("checkBox_19")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_20.setObjectName("checkBox_20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_21.setObjectName("checkBox_21")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_22.setObjectName("checkBox_22")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_23.setObjectName("checkBox_23")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_24.setObjectName("checkBox_24")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_25.setObjectName("checkBox_25")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_26.setObjectName("checkBox_26")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_27.setObjectName("checkBox_27")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_28.setObjectName("checkBox_28")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_29.setObjectName("checkBox_29")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_30.setObjectName("checkBox_30")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkBox_30)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_31.setObjectName("checkBox_31")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_32.setObjectName("checkBox_32")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.checkBox_32)
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_33.setObjectName("checkBox_33")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.checkBox_33)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_34.setObjectName("checkBox_34")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.checkBox_34)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_35.setObjectName("checkBox_35")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.checkBox_35)
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        self.checkBox_40.toggled['bool'].connect(self.groupBox.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Post Statistics"))
        self.checkBox_36.setText(_translate("Form", "Like count"))
        self.checkBox_37.setText(_translate("Form", "Reaction count"))
        self.checkBox_38.setText(_translate("Form", "Share count"))
        self.checkBox_39.setText(_translate("Form", "Comment count"))
        self.checkBox_40.setText(_translate("Form", "Customize post fields"))
        self.groupBox.setTitle(_translate("Form", "Post Fields"))
        self.checkBox.setText(_translate("Form", "id"))
        self.checkBox_2.setText(_translate("Form", "admin_creator"))
        self.checkBox_3.setText(_translate("Form", "application"))
        self.checkBox_4.setText(_translate("Form", "call_to_action"))
        self.checkBox_5.setText(_translate("Form", "caption"))
        self.checkBox_6.setText(_translate("Form", "created_time"))
        self.checkBox_7.setText(_translate("Form", "description"))
        self.checkBox_8.setText(_translate("Form", "field_targeting"))
        self.checkBox_9.setText(_translate("Form", "from"))
        self.checkBox_10.setText(_translate("Form", "icon"))
        self.checkBox_11.setText(_translate("Form", "instagram_eligibility"))
        self.checkBox_12.setText(_translate("Form", "is_hidden"))
        self.checkBox_13.setText(_translate("Form", "is_instagram_eligable"))
        self.checkBox_14.setText(_translate("Form", "is_published"))
        self.checkBox_15.setText(_translate("Form", "link"))
        self.checkBox_16.setText(_translate("Form", "message"))
        self.checkBox_17.setText(_translate("Form", "message_tags"))
        self.checkBox_18.setText(_translate("Form", "name"))
        self.checkBox_19.setText(_translate("Form", "object_id"))
        self.checkBox_20.setText(_translate("Form", "parent_id"))
        self.checkBox_21.setText(_translate("Form", "permalink_url"))
        self.checkBox_22.setText(_translate("Form", "picture"))
        self.checkBox_23.setText(_translate("Form", "place"))
        self.checkBox_24.setText(_translate("Form", "privacy"))
        self.checkBox_25.setText(_translate("Form", "properties"))
        self.checkBox_26.setText(_translate("Form", "shares"))
        self.checkBox_27.setText(_translate("Form", "source"))
        self.checkBox_28.setText(_translate("Form", "status_type"))
        self.checkBox_29.setText(_translate("Form", "story"))
        self.checkBox_30.setText(_translate("Form", "story_tags"))
        self.checkBox_31.setText(_translate("Form", "targetting"))
        self.checkBox_32.setText(_translate("Form", "to"))
        self.checkBox_33.setText(_translate("Form", "type"))
        self.checkBox_34.setText(_translate("Form", "updated_time"))
        self.checkBox_35.setText(_translate("Form", "with_tags"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

